name: chache build
env:
  CWA_GITHUB_REPO_NAME: "aws/amazon-cloudwatch-agent"
  S3_INTEGRATION_BUCKET: "terraform-integration-test"
  CACHE_DIR: "uniform-build-env-test/cache_build_env"

on:
  push:
    branches:
      - CWQS-739
  workflow_dispatch:
jobs:
  cache:
    name: build cache
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.TERRAFORM_AWS_ASSUME_ROLE }}
          aws-region: us-west-2
      - uses: actions/checkout@v3
        with:
          repository: ${{env.CWA_GITHUB_REPO_NAME}}
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ~1.19.2
      - name: Cache binaries
        id: cached_binaries
        uses: actions/cache@v3
        with:
          key: "cached_binaries_${{ github.sha }}"
          path: go.mod
      - name: Build Uniform Build Env
        if: contains(inputs.BucketKey, 'test') == false || steps.cached_binaries.outputs.cache-hit == false
        run: |
          cd packaging/uniformBuild
          go build .
